/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {FiatDepositBankAccountModel} from '../model/FiatDepositBankAccountModel';

/**
* FiatDeposit service.
* @module api/FiatDepositApi
* @version 3.0
*/
export class FiatDepositApi {

    /**
    * Constructs a new FiatDepositApi. 
    * @alias module:api/FiatDepositApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiV3DepositsFiatBankGet operation.
     * @callback moduleapi/FiatDepositApi~apiV3DepositsFiatBankGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/FiatDepositBankAccountModel>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.currencySymbol 
     * @param {module:api/FiatDepositApi~apiV3DepositsFiatBankGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV3DepositsFiatBankGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'currencySymbol': opts['currencySymbol']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [FiatDepositBankAccountModel];

      return this.apiClient.callApi(
        '/api/v3/deposits/fiat/bank', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV3DepositsFiatBankSendSmsSlugGet operation.
     * @callback moduleapi/FiatDepositApi~apiV3DepositsFiatBankSendSmsSlugGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} slug 
     * @param {Object} opts Optional parameters
     * @param {String} opts.currencySymbol 
     * @param {module:api/FiatDepositApi~apiV3DepositsFiatBankSendSmsSlugGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV3DepositsFiatBankSendSmsSlugGet(slug, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'slug' is set
      if (slug === undefined || slug === null) {
        throw new Error("Missing the required parameter 'slug' when calling apiV3DepositsFiatBankSendSmsSlugGet");
      }

      let pathParams = {
        'slug': slug
      };
      let queryParams = {
        'currencySymbol': opts['currencySymbol']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v3/deposits/fiat/bank/send-sms/{slug}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV3DepositsFiatBankSlugGet operation.
     * @callback moduleapi/FiatDepositApi~apiV3DepositsFiatBankSlugGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FiatDepositBankAccountModel{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} slug 
     * @param {Object} opts Optional parameters
     * @param {String} opts.currencySymbol 
     * @param {module:api/FiatDepositApi~apiV3DepositsFiatBankSlugGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV3DepositsFiatBankSlugGet(slug, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'slug' is set
      if (slug === undefined || slug === null) {
        throw new Error("Missing the required parameter 'slug' when calling apiV3DepositsFiatBankSlugGet");
      }

      let pathParams = {
        'slug': slug
      };
      let queryParams = {
        'currencySymbol': opts['currencySymbol']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = FiatDepositBankAccountModel;

      return this.apiClient.callApi(
        '/api/v3/deposits/fiat/bank/{slug}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}