/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";

/**
* SupportPlatforms service.
* @module api/SupportPlatformsApi
* @version 3.0
*/
export class SupportPlatformsApi {

    /**
    * Constructs a new SupportPlatformsApi. 
    * @alias module:api/SupportPlatformsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiV3SupportPlatformsGet operation.
     * @callback moduleapi/SupportPlatformsApi~apiV3SupportPlatformsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/SupportPlatformsApi~apiV3SupportPlatformsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV3SupportPlatformsGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v3/support-platforms', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV3SupportPlatformsZendeskChatJwtPlatformGet operation.
     * @callback moduleapi/SupportPlatformsApi~apiV3SupportPlatformsZendeskChatJwtPlatformGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} platform 
     * @param {module:api/SupportPlatformsApi~apiV3SupportPlatformsZendeskChatJwtPlatformGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV3SupportPlatformsZendeskChatJwtPlatformGet(platform, callback) {
      
      let postBody = null;
      // verify the required parameter 'platform' is set
      if (platform === undefined || platform === null) {
        throw new Error("Missing the required parameter 'platform' when calling apiV3SupportPlatformsZendeskChatJwtPlatformGet");
      }

      let pathParams = {
        'platform': platform
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v3/support-platforms/zendesk/chat-jwt/{platform}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV3SupportPlatformsZendeskMobileJwtPlatformPost operation.
     * @callback moduleapi/SupportPlatformsApi~apiV3SupportPlatformsZendeskMobileJwtPlatformPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} platform 
     * @param {Object} opts Optional parameters
     * @param {String} opts.userToken 
     * @param {module:api/SupportPlatformsApi~apiV3SupportPlatformsZendeskMobileJwtPlatformPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV3SupportPlatformsZendeskMobileJwtPlatformPost(platform, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'platform' is set
      if (platform === undefined || platform === null) {
        throw new Error("Missing the required parameter 'platform' when calling apiV3SupportPlatformsZendeskMobileJwtPlatformPost");
      }

      let pathParams = {
        'platform': platform
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'user_token': opts['userToken']
      };

      let authNames = ['Bearer'];
      let contentTypes = ['multipart/form-data'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v3/support-platforms/zendesk/mobile-jwt/{platform}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV3SupportPlatformsZendeskSessionsPost operation.
     * @callback moduleapi/SupportPlatformsApi~apiV3SupportPlatformsZendeskSessionsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/SupportPlatformsApi~apiV3SupportPlatformsZendeskSessionsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV3SupportPlatformsZendeskSessionsPost(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v3/support-platforms/zendesk/sessions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}