/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BankCommissionOutputModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BankCommissionOutputModelTests
    {
        // TODO uncomment below to declare an instance variable for BankCommissionOutputModel
        //private BankCommissionOutputModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BankCommissionOutputModel
            //instance = new BankCommissionOutputModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BankCommissionOutputModel
        /// </summary>
        [Test]
        public void BankCommissionOutputModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BankCommissionOutputModel
            //Assert.IsInstanceOfType<BankCommissionOutputModel> (instance, "variable 'instance' is a BankCommissionOutputModel");
        }


        /// <summary>
        /// Test the property 'DepositFee'
        /// </summary>
        [Test]
        public void DepositFeeTest()
        {
            // TODO unit test for the property 'DepositFee'
        }
        /// <summary>
        /// Test the property 'WithdrawalFee'
        /// </summary>
        [Test]
        public void WithdrawalFeeTest()
        {
            // TODO unit test for the property 'WithdrawalFee'
        }
        /// <summary>
        /// Test the property 'DepositTax'
        /// </summary>
        [Test]
        public void DepositTaxTest()
        {
            // TODO unit test for the property 'DepositTax'
        }
        /// <summary>
        /// Test the property 'WithdrawalTax'
        /// </summary>
        [Test]
        public void WithdrawalTaxTest()
        {
            // TODO unit test for the property 'WithdrawalTax'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

    }

}
