/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CryptoWithdrawalDeleteInputModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CryptoWithdrawalDeleteInputModelTests
    {
        // TODO uncomment below to declare an instance variable for CryptoWithdrawalDeleteInputModel
        //private CryptoWithdrawalDeleteInputModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CryptoWithdrawalDeleteInputModel
            //instance = new CryptoWithdrawalDeleteInputModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CryptoWithdrawalDeleteInputModel
        /// </summary>
        [Test]
        public void CryptoWithdrawalDeleteInputModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CryptoWithdrawalDeleteInputModel
            //Assert.IsInstanceOfType<CryptoWithdrawalDeleteInputModel> (instance, "variable 'instance' is a CryptoWithdrawalDeleteInputModel");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

    }

}
