/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CryptoCurrencySymbol
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CryptoCurrencySymbolTests
    {
        // TODO uncomment below to declare an instance variable for CryptoCurrencySymbol
        //private CryptoCurrencySymbol instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CryptoCurrencySymbol
            //instance = new CryptoCurrencySymbol();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CryptoCurrencySymbol
        /// </summary>
        [Test]
        public void CryptoCurrencySymbolInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CryptoCurrencySymbol
            //Assert.IsInstanceOfType<CryptoCurrencySymbol> (instance, "variable 'instance' is a CryptoCurrencySymbol");
        }



    }

}
