/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MobileSettingModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MobileSettingModelTests
    {
        // TODO uncomment below to declare an instance variable for MobileSettingModel
        //private MobileSettingModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MobileSettingModel
            //instance = new MobileSettingModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MobileSettingModel
        /// </summary>
        [Test]
        public void MobileSettingModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MobileSettingModel
            //Assert.IsInstanceOfType<MobileSettingModel> (instance, "variable 'instance' is a MobileSettingModel");
        }


        /// <summary>
        /// Test the property 'LanguageSettings'
        /// </summary>
        [Test]
        public void LanguageSettingsTest()
        {
            // TODO unit test for the property 'LanguageSettings'
        }
        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Test]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }
        /// <summary>
        /// Test the property 'EuroIsEnable'
        /// </summary>
        [Test]
        public void EuroIsEnableTest()
        {
            // TODO unit test for the property 'EuroIsEnable'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }

    }

}
