/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserTradeFeeRateOutputModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserTradeFeeRateOutputModelTests
    {
        // TODO uncomment below to declare an instance variable for UserTradeFeeRateOutputModel
        //private UserTradeFeeRateOutputModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserTradeFeeRateOutputModel
            //instance = new UserTradeFeeRateOutputModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserTradeFeeRateOutputModel
        /// </summary>
        [Test]
        public void UserTradeFeeRateOutputModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserTradeFeeRateOutputModel
            //Assert.IsInstanceOfType<UserTradeFeeRateOutputModel> (instance, "variable 'instance' is a UserTradeFeeRateOutputModel");
        }


        /// <summary>
        /// Test the property 'PairId'
        /// </summary>
        [Test]
        public void PairIdTest()
        {
            // TODO unit test for the property 'PairId'
        }
        /// <summary>
        /// Test the property 'PairSymbol'
        /// </summary>
        [Test]
        public void PairSymbolTest()
        {
            // TODO unit test for the property 'PairSymbol'
        }
        /// <summary>
        /// Test the property 'OrderMethod'
        /// </summary>
        [Test]
        public void OrderMethodTest()
        {
            // TODO unit test for the property 'OrderMethod'
        }
        /// <summary>
        /// Test the property 'MakerFeePercentage'
        /// </summary>
        [Test]
        public void MakerFeePercentageTest()
        {
            // TODO unit test for the property 'MakerFeePercentage'
        }
        /// <summary>
        /// Test the property 'TakerFeePercentage'
        /// </summary>
        [Test]
        public void TakerFeePercentageTest()
        {
            // TODO unit test for the property 'TakerFeePercentage'
        }
        /// <summary>
        /// Test the property 'TaxPercentage'
        /// </summary>
        [Test]
        public void TaxPercentageTest()
        {
            // TODO unit test for the property 'TaxPercentage'
        }
        /// <summary>
        /// Test the property 'HasActiveCoupon'
        /// </summary>
        [Test]
        public void HasActiveCouponTest()
        {
            // TODO unit test for the property 'HasActiveCoupon'
        }

    }

}
