/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserDonationRequestModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserDonationRequestModelTests
    {
        // TODO uncomment below to declare an instance variable for UserDonationRequestModel
        //private UserDonationRequestModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserDonationRequestModel
            //instance = new UserDonationRequestModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserDonationRequestModel
        /// </summary>
        [Test]
        public void UserDonationRequestModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserDonationRequestModel
            //Assert.IsInstanceOfType<UserDonationRequestModel> (instance, "variable 'instance' is a UserDonationRequestModel");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'BankId'
        /// </summary>
        [Test]
        public void BankIdTest()
        {
            // TODO unit test for the property 'BankId'
        }

    }

}
