/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BtcTurkAp30);
  }
}(this, function(expect, BtcTurkAp30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BtcTurkAp30.UserAgreementApi();
  });

  describe('(package)', function() {
    describe('UserAgreementApi', function() {
      describe('apiV3UserAgreementGet', function() {
        it('should call apiV3UserAgreementGet successfully', function(done) {
          // TODO: uncomment apiV3UserAgreementGet call and complete the assertions
          /*

          instance.apiV3UserAgreementGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(BtcTurkAp30.UserAgreementModel);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV3UserAgreementPost', function() {
        it('should call apiV3UserAgreementPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV3UserAgreementPost call
          /*
          var opts = {};

          instance.apiV3UserAgreementPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV3UserAgreementRiskDisclosureCurrencySymbolGet', function() {
        it('should call apiV3UserAgreementRiskDisclosureCurrencySymbolGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV3UserAgreementRiskDisclosureCurrencySymbolGet call and complete the assertions
          /*
          var opts = {};

          instance.apiV3UserAgreementRiskDisclosureCurrencySymbolGet(symbol, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BtcTurkAp30.CheckCurrencyRiskAgreementResponseModel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV3UserAgreementRiskDisclosurePairPairSymbolGet', function() {
        it('should call apiV3UserAgreementRiskDisclosurePairPairSymbolGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV3UserAgreementRiskDisclosurePairPairSymbolGet call and complete the assertions
          /*

          instance.apiV3UserAgreementRiskDisclosurePairPairSymbolGet(pairSymbol, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BtcTurkAp30.CheckPairRiskAgreementResponseModel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV3UserAgreementSlugGet', function() {
        it('should call apiV3UserAgreementSlugGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV3UserAgreementSlugGet call and complete the assertions
          /*

          instance.apiV3UserAgreementSlugGet(slug, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BtcTurkAp30.UserAgreementModel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV3UserAgreementSlugGet_0', function() {
        it('should call apiV3UserAgreementSlugGet_0 successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV3UserAgreementSlugGet_0 call and complete the assertions
          /*

          instance.apiV3UserAgreementSlugGet_0(slug, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BtcTurkAp30.UserAgreementModel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV3UserAgreementSlugPost', function() {
        it('should call apiV3UserAgreementSlugPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV3UserAgreementSlugPost call
          /*

          instance.apiV3UserAgreementSlugPost(slug, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
