# coding: utf-8

"""
    BtcTurk API 3.0

    White label exchange API documentation.  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: development@btctrader.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LanguageInfoModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'language_culture': 'str',
        'version': 'str'
    }

    attribute_map = {
        'language_culture': 'languageCulture',
        'version': 'version'
    }

    def __init__(self, language_culture=None, version=None):  # noqa: E501
        """LanguageInfoModel - a model defined in Swagger"""  # noqa: E501
        self._language_culture = None
        self._version = None
        self.discriminator = None
        if language_culture is not None:
            self.language_culture = language_culture
        if version is not None:
            self.version = version

    @property
    def language_culture(self):
        """Gets the language_culture of this LanguageInfoModel.  # noqa: E501


        :return: The language_culture of this LanguageInfoModel.  # noqa: E501
        :rtype: str
        """
        return self._language_culture

    @language_culture.setter
    def language_culture(self, language_culture):
        """Sets the language_culture of this LanguageInfoModel.


        :param language_culture: The language_culture of this LanguageInfoModel.  # noqa: E501
        :type: str
        """

        self._language_culture = language_culture

    @property
    def version(self):
        """Gets the version of this LanguageInfoModel.  # noqa: E501


        :return: The version of this LanguageInfoModel.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this LanguageInfoModel.


        :param version: The version of this LanguageInfoModel.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LanguageInfoModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LanguageInfoModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
