/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines CryptoCurrencySymbol
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum CryptoCurrencySymbol
    {
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 1,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 2,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 3,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 4,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 5,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 6,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 7,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 8,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 9,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 10,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 11,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 12,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 13,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 14,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 15,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 16,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 17,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 18,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 19,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 20,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 21,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 22,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 23,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 24,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 25,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 26,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 27,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 28,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 29,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 30,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 31,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 32,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 33,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 34,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 35,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 36,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 37,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 38,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 39,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 40,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 41,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 42,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 43,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 44,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 45,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 46,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 47,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 48,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 49,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 50,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 51,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 52,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 53,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 54,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 55,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 56,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 57,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 58,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 59,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 60,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 61,
        /// <summary>
        /// Enum NUMBER_null for value: null
        /// </summary>
        [EnumMember(Value = null)]
        NUMBER_null = 62    }
}
