/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PairLimit
    /// </summary>
    [DataContract]
        public partial class PairLimit :  IEquatable<PairLimit>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PairLimit" /> class.
        /// </summary>
        /// <param name="numerator">numerator.</param>
        /// <param name="denominator">denominator.</param>
        /// <param name="minExchangeValue">minExchangeValue.</param>
        public PairLimit(string numerator = default(string), string denominator = default(string), double? minExchangeValue = default(double?))
        {
            this.Numerator = numerator;
            this.Denominator = denominator;
            this.MinExchangeValue = minExchangeValue;
        }
        
        /// <summary>
        /// Gets or Sets Numerator
        /// </summary>
        [DataMember(Name="numerator", EmitDefaultValue=false)]
        public string Numerator { get; set; }

        /// <summary>
        /// Gets or Sets Denominator
        /// </summary>
        [DataMember(Name="denominator", EmitDefaultValue=false)]
        public string Denominator { get; set; }

        /// <summary>
        /// Gets or Sets MinExchangeValue
        /// </summary>
        [DataMember(Name="minExchangeValue", EmitDefaultValue=false)]
        public double? MinExchangeValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PairLimit {\n");
            sb.Append("  Numerator: ").Append(Numerator).Append("\n");
            sb.Append("  Denominator: ").Append(Denominator).Append("\n");
            sb.Append("  MinExchangeValue: ").Append(MinExchangeValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PairLimit);
        }

        /// <summary>
        /// Returns true if PairLimit instances are equal
        /// </summary>
        /// <param name="input">Instance of PairLimit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PairLimit input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Numerator == input.Numerator ||
                    (this.Numerator != null &&
                    this.Numerator.Equals(input.Numerator))
                ) && 
                (
                    this.Denominator == input.Denominator ||
                    (this.Denominator != null &&
                    this.Denominator.Equals(input.Denominator))
                ) && 
                (
                    this.MinExchangeValue == input.MinExchangeValue ||
                    (this.MinExchangeValue != null &&
                    this.MinExchangeValue.Equals(input.MinExchangeValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Numerator != null)
                    hashCode = hashCode * 59 + this.Numerator.GetHashCode();
                if (this.Denominator != null)
                    hashCode = hashCode * 59 + this.Denominator.GetHashCode();
                if (this.MinExchangeValue != null)
                    hashCode = hashCode * 59 + this.MinExchangeValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
