/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FiatDepositApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FiatDepositApiTests
    {
        private FiatDepositApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FiatDepositApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FiatDepositApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FiatDepositApi
            //Assert.IsInstanceOfType(typeof(FiatDepositApi), instance, "instance is a FiatDepositApi");
        }

        /// <summary>
        /// Test ApiV3DepositsFiatBankGet
        /// </summary>
        [Test]
        public void ApiV3DepositsFiatBankGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string currencySymbol = null;
            //var response = instance.ApiV3DepositsFiatBankGet(currencySymbol);
            //Assert.IsInstanceOf<List<FiatDepositBankAccountModel>> (response, "response is List<FiatDepositBankAccountModel>");
        }
        /// <summary>
        /// Test ApiV3DepositsFiatBankSendSmsSlugGet
        /// </summary>
        [Test]
        public void ApiV3DepositsFiatBankSendSmsSlugGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string slug = null;
            //string currencySymbol = null;
            //instance.ApiV3DepositsFiatBankSendSmsSlugGet(slug, currencySymbol);
            
        }
        /// <summary>
        /// Test ApiV3DepositsFiatBankSlugGet
        /// </summary>
        [Test]
        public void ApiV3DepositsFiatBankSlugGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string slug = null;
            //string currencySymbol = null;
            //var response = instance.ApiV3DepositsFiatBankSlugGet(slug, currencySymbol);
            //Assert.IsInstanceOf<FiatDepositBankAccountModel> (response, "response is FiatDepositBankAccountModel");
        }
    }

}
