/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReportApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ReportApiTests
    {
        private ReportApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ReportApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ReportApi
            //Assert.IsInstanceOfType(typeof(ReportApi), instance, "instance is a ReportApi");
        }

        /// <summary>
        /// Test ApiV3ReportDepositAndWithdrawalPost
        /// </summary>
        [Test]
        public void ApiV3ReportDepositAndWithdrawalPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReportDepositWithdrawalInputModel body = null;
            //instance.ApiV3ReportDepositAndWithdrawalPost(body);
            
        }
        /// <summary>
        /// Test ApiV3ReportGet
        /// </summary>
        [Test]
        public void ApiV3ReportGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiV3ReportGet();
            
        }
        /// <summary>
        /// Test ApiV3ReportTradeHistoryPost
        /// </summary>
        [Test]
        public void ApiV3ReportTradeHistoryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReportTradeHistoryInputModel body = null;
            //instance.ApiV3ReportTradeHistoryPost(body);
            
        }
        /// <summary>
        /// Test ApiV3ReportTransactionHistoryPost
        /// </summary>
        [Test]
        public void ApiV3ReportTransactionHistoryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReportTransactionHistoryInputModel body = null;
            //instance.ApiV3ReportTransactionHistoryPost(body);
            
        }
    }

}
