/* 
 * BtcTurk API 3.0
 *
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserAgreementApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UserAgreementApiTests
    {
        private UserAgreementApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserAgreementApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserAgreementApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UserAgreementApi
            //Assert.IsInstanceOfType(typeof(UserAgreementApi), instance, "instance is a UserAgreementApi");
        }

        /// <summary>
        /// Test ApiV3UserAgreementGet
        /// </summary>
        [Test]
        public void ApiV3UserAgreementGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiV3UserAgreementGet();
            //Assert.IsInstanceOf<List<UserAgreementModel>> (response, "response is List<UserAgreementModel>");
        }
        /// <summary>
        /// Test ApiV3UserAgreementPost
        /// </summary>
        [Test]
        public void ApiV3UserAgreementPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserAgreementApproveModel body = null;
            //instance.ApiV3UserAgreementPost(body);
            
        }
        /// <summary>
        /// Test ApiV3UserAgreementRiskDisclosureCurrencySymbolGet
        /// </summary>
        [Test]
        public void ApiV3UserAgreementRiskDisclosureCurrencySymbolGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string symbol = null;
            //CurrencyTransferType transferType = null;
            //var response = instance.ApiV3UserAgreementRiskDisclosureCurrencySymbolGet(symbol, transferType);
            //Assert.IsInstanceOf<CheckCurrencyRiskAgreementResponseModel> (response, "response is CheckCurrencyRiskAgreementResponseModel");
        }
        /// <summary>
        /// Test ApiV3UserAgreementRiskDisclosurePairPairSymbolGet
        /// </summary>
        [Test]
        public void ApiV3UserAgreementRiskDisclosurePairPairSymbolGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pairSymbol = null;
            //var response = instance.ApiV3UserAgreementRiskDisclosurePairPairSymbolGet(pairSymbol);
            //Assert.IsInstanceOf<CheckPairRiskAgreementResponseModel> (response, "response is CheckPairRiskAgreementResponseModel");
        }
        /// <summary>
        /// Test ApiV3UserAgreementSlugGet
        /// </summary>
        [Test]
        public void ApiV3UserAgreementSlugGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string slug = null;
            //var response = instance.ApiV3UserAgreementSlugGet(slug);
            //Assert.IsInstanceOf<UserAgreementModel> (response, "response is UserAgreementModel");
        }
        /// <summary>
        /// Test ApiV3UserAgreementSlugGet_0
        /// </summary>
        [Test]
        public void ApiV3UserAgreementSlugGet_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string slug = null;
            //var response = instance.ApiV3UserAgreementSlugGet_0(slug);
            //Assert.IsInstanceOf<UserAgreementModel> (response, "response is UserAgreementModel");
        }
        /// <summary>
        /// Test ApiV3UserAgreementSlugPost
        /// </summary>
        [Test]
        public void ApiV3UserAgreementSlugPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string slug = null;
            //instance.ApiV3UserAgreementSlugPost(slug);
            
        }
    }

}
