/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AccountAddressModel;
import io.swagger.client.model.CreateSplashScreenLoginRequestModel;
import io.swagger.client.model.OrderMethod;
import io.swagger.client.model.UserAllLimitsModel;
import io.swagger.client.model.UserTradeFeeRateErrorModel;
import io.swagger.client.model.UserTradeFeeRateOutputModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AccountApi
 */
@Ignore
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AccountAddressPutTest() throws Exception {
        AccountAddressModel body = null;
        api.apiV3AccountAddressPut(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AccountBuySellInfoGetTest() throws Exception {
        api.apiV3AccountBuySellInfoGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AccountFeaturesGetTest() throws Exception {
        api.apiV3AccountFeaturesGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AccountLimitsGetTest() throws Exception {
        String currencySymbol = null;
        UserAllLimitsModel response = api.apiV3AccountLimitsGet(currencySymbol);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AccountPdpaPostTest() throws Exception {
        String value = null;
        api.apiV3AccountPdpaPost(value);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AccountSplashScreenLoginPostTest() throws Exception {
        CreateSplashScreenLoginRequestModel body = null;
        api.apiV3AccountSplashScreenLoginPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AccountTradeFeeRatesGetTest() throws Exception {
        OrderMethod orderMethod = null;
        String pairSymbol = null;
        UserTradeFeeRateOutputModel response = api.apiV3AccountTradeFeeRatesGet(orderMethod, pairSymbol);

        // TODO: test validations
    }
}
