/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BugBountyNoticeRequestModel;
import io.swagger.client.model.HallOfFrameResponseModel;
import io.swagger.client.model.ReturnModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for BugBountyApi
 */
@Ignore
public class BugBountyApiTest {

    private final BugBountyApi api = new BugBountyApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3BugBountiesHallOfFameGetTest() throws Exception {
        List<HallOfFrameResponseModel> response = api.apiV3BugBountiesHallOfFameGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3BugBountiesPostTest() throws Exception {
        BugBountyNoticeRequestModel body = null;
        String xClientİd = null;
        api.apiV3BugBountiesPost(body, xClientİd);

        // TODO: test validations
    }
}
