/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for HomeApi
 */
@Ignore
public class HomeApiTest {

    private final HomeApi api = new HomeApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiResourcesLanguageGetTest() throws Exception {
        api.apiResourcesLanguageGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiResourcesLanguageJsonGetTest() throws Exception {
        String language = null;
        Integer brokerId = null;
        api.apiResourcesLanguageJsonGet(language, brokerId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiResourcesLocationGetTest() throws Exception {
        api.apiResourcesLocationGet();

        // TODO: test validations
    }
}
