/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.JumioKycIdentityVerificationRequestModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for KnowYourCustomerApi
 */
@Ignore
public class KnowYourCustomerApiTest {

    private final KnowYourCustomerApi api = new KnowYourCustomerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AccountKycPostTest() throws Exception {
        JumioKycIdentityVerificationRequestModel body = null;
        api.apiV3AccountKycPost(body);

        // TODO: test validations
    }
}
