/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class AlarmTypes.
 * @enum {Number}
 * @readonly
 */
const AlarmTypes = {
  /**
   * value: 
   * @const
   */
  _null: ,

  /**
   * value: 
   * @const
   */
  _null: ,

  /**
   * value: 
   * @const
   */
  _null: ,

  /**
   * value: 
   * @const
   */
  _null: ,

  /**
   * Returns a <code>AlarmTypes</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/AlarmTypes} The enum <code>AlarmTypes</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {AlarmTypes};