/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BankCommissionOutputModel model module.
 * @module model/BankCommissionOutputModel
 * @version 3.0
 */
export class BankCommissionOutputModel {
  /**
   * Constructs a new <code>BankCommissionOutputModel</code>.
   * @alias module:model/BankCommissionOutputModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BankCommissionOutputModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BankCommissionOutputModel} obj Optional instance to populate.
   * @return {module:model/BankCommissionOutputModel} The populated <code>BankCommissionOutputModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BankCommissionOutputModel();
      if (data.hasOwnProperty('depositFee'))
        obj.depositFee = ApiClient.convertToType(data['depositFee'], 'Number');
      if (data.hasOwnProperty('withdrawalFee'))
        obj.withdrawalFee = ApiClient.convertToType(data['withdrawalFee'], 'Number');
      if (data.hasOwnProperty('depositTax'))
        obj.depositTax = ApiClient.convertToType(data['depositTax'], 'Number');
      if (data.hasOwnProperty('withdrawalTax'))
        obj.withdrawalTax = ApiClient.convertToType(data['withdrawalTax'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} depositFee
 */
BankCommissionOutputModel.prototype.depositFee = undefined;

/**
 * @member {Number} withdrawalFee
 */
BankCommissionOutputModel.prototype.withdrawalFee = undefined;

/**
 * @member {Number} depositTax
 */
BankCommissionOutputModel.prototype.depositTax = undefined;

/**
 * @member {Number} withdrawalTax
 */
BankCommissionOutputModel.prototype.withdrawalTax = undefined;

/**
 * @member {String} currency
 */
BankCommissionOutputModel.prototype.currency = undefined;

