/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CheckPairRiskAgreementResponseModel model module.
 * @module model/CheckPairRiskAgreementResponseModel
 * @version 3.0
 */
export class CheckPairRiskAgreementResponseModel {
  /**
   * Constructs a new <code>CheckPairRiskAgreementResponseModel</code>.
   * @alias module:model/CheckPairRiskAgreementResponseModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CheckPairRiskAgreementResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CheckPairRiskAgreementResponseModel} obj Optional instance to populate.
   * @return {module:model/CheckPairRiskAgreementResponseModel} The populated <code>CheckPairRiskAgreementResponseModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckPairRiskAgreementResponseModel();
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('required'))
        obj.required = ApiClient.convertToType(data['required'], 'String');
      if (data.hasOwnProperty('approved'))
        obj.approved = ApiClient.convertToType(data['approved'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} slug
 */
CheckPairRiskAgreementResponseModel.prototype.slug = undefined;

/**
 * @member {String} required
 */
CheckPairRiskAgreementResponseModel.prototype.required = undefined;

/**
 * @member {Boolean} approved
 */
CheckPairRiskAgreementResponseModel.prototype.approved = undefined;

