/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LanguageInfoModel model module.
 * @module model/LanguageInfoModel
 * @version 3.0
 */
export class LanguageInfoModel {
  /**
   * Constructs a new <code>LanguageInfoModel</code>.
   * @alias module:model/LanguageInfoModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LanguageInfoModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LanguageInfoModel} obj Optional instance to populate.
   * @return {module:model/LanguageInfoModel} The populated <code>LanguageInfoModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LanguageInfoModel();
      if (data.hasOwnProperty('languageCulture'))
        obj.languageCulture = ApiClient.convertToType(data['languageCulture'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} languageCulture
 */
LanguageInfoModel.prototype.languageCulture = undefined;

/**
 * @member {String} version
 */
LanguageInfoModel.prototype.version = undefined;

