/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LanguageInfoModel} from './LanguageInfoModel';

/**
 * The LanguageSettingModel model module.
 * @module model/LanguageSettingModel
 * @version 3.0
 */
export class LanguageSettingModel {
  /**
   * Constructs a new <code>LanguageSettingModel</code>.
   * @alias module:model/LanguageSettingModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LanguageSettingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LanguageSettingModel} obj Optional instance to populate.
   * @return {module:model/LanguageSettingModel} The populated <code>LanguageSettingModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LanguageSettingModel();
      if (data.hasOwnProperty('languageList'))
        obj.languageList = ApiClient.convertToType(data['languageList'], [LanguageInfoModel]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/LanguageInfoModel>} languageList
 */
LanguageSettingModel.prototype.languageList = undefined;

