/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AkbankDirektLimit} from './AkbankDirektLimit';
import {BankLimit} from './BankLimit';
import {CurrencyLimit} from './CurrencyLimit';
import {PairLimit} from './PairLimit';
import {PaparaLimit} from './PaparaLimit';

/**
 * The LimitOutputModel model module.
 * @module model/LimitOutputModel
 * @version 3.0
 */
export class LimitOutputModel {
  /**
   * Constructs a new <code>LimitOutputModel</code>.
   * @alias module:model/LimitOutputModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LimitOutputModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LimitOutputModel} obj Optional instance to populate.
   * @return {module:model/LimitOutputModel} The populated <code>LimitOutputModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LimitOutputModel();
      if (data.hasOwnProperty('papara'))
        obj.papara = PaparaLimit.constructFromObject(data['papara']);
      if (data.hasOwnProperty('akbankDirekt'))
        obj.akbankDirekt = AkbankDirektLimit.constructFromObject(data['akbankDirekt']);
      if (data.hasOwnProperty('bank'))
        obj.bank = BankLimit.constructFromObject(data['bank']);
      if (data.hasOwnProperty('currencies'))
        obj.currencies = ApiClient.convertToType(data['currencies'], [CurrencyLimit]);
      if (data.hasOwnProperty('pairs'))
        obj.pairs = ApiClient.convertToType(data['pairs'], [PairLimit]);
      if (data.hasOwnProperty('countryCode'))
        obj.countryCode = ApiClient.convertToType(data['countryCode'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/PaparaLimit} papara
 */
LimitOutputModel.prototype.papara = undefined;

/**
 * @member {module:model/AkbankDirektLimit} akbankDirekt
 */
LimitOutputModel.prototype.akbankDirekt = undefined;

/**
 * @member {module:model/BankLimit} bank
 */
LimitOutputModel.prototype.bank = undefined;

/**
 * @member {Array.<module:model/CurrencyLimit>} currencies
 */
LimitOutputModel.prototype.currencies = undefined;

/**
 * @member {Array.<module:model/PairLimit>} pairs
 */
LimitOutputModel.prototype.pairs = undefined;

/**
 * @member {String} countryCode
 */
LimitOutputModel.prototype.countryCode = undefined;

