/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PairLimit model module.
 * @module model/PairLimit
 * @version 3.0
 */
export class PairLimit {
  /**
   * Constructs a new <code>PairLimit</code>.
   * @alias module:model/PairLimit
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PairLimit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PairLimit} obj Optional instance to populate.
   * @return {module:model/PairLimit} The populated <code>PairLimit</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PairLimit();
      if (data.hasOwnProperty('numerator'))
        obj.numerator = ApiClient.convertToType(data['numerator'], 'String');
      if (data.hasOwnProperty('denominator'))
        obj.denominator = ApiClient.convertToType(data['denominator'], 'String');
      if (data.hasOwnProperty('minExchangeValue'))
        obj.minExchangeValue = ApiClient.convertToType(data['minExchangeValue'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} numerator
 */
PairLimit.prototype.numerator = undefined;

/**
 * @member {String} denominator
 */
PairLimit.prototype.denominator = undefined;

/**
 * @member {Number} minExchangeValue
 */
PairLimit.prototype.minExchangeValue = undefined;

