/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserDonationRequestModel model module.
 * @module model/UserDonationRequestModel
 * @version 3.0
 */
export class UserDonationRequestModel {
  /**
   * Constructs a new <code>UserDonationRequestModel</code>.
   * @alias module:model/UserDonationRequestModel
   * @class
   * @param amount {String} 
   * @param bankId {Number} 
   */
  constructor(amount, bankId) {
    this.amount = amount;
    this.bankId = bankId;
  }

  /**
   * Constructs a <code>UserDonationRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserDonationRequestModel} obj Optional instance to populate.
   * @return {module:model/UserDonationRequestModel} The populated <code>UserDonationRequestModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserDonationRequestModel();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('bankId'))
        obj.bankId = ApiClient.convertToType(data['bankId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} amount
 */
UserDonationRequestModel.prototype.amount = undefined;

/**
 * @member {Number} bankId
 */
UserDonationRequestModel.prototype.bankId = undefined;

