/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AnnouncementDetailModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-22T13:33:34.912136+03:00[Europe/Istanbul]")
public class AnnouncementDetailModel {
  @SerializedName("content")
  private String content = null;

  @SerializedName("metaTitle")
  private String metaTitle = null;

  @SerializedName("metaDescription")
  private String metaDescription = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("seoUrl")
  private String seoUrl = null;

  @SerializedName("releaseDate")
  private Long releaseDate = null;

  public AnnouncementDetailModel content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @Schema(description = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public AnnouncementDetailModel metaTitle(String metaTitle) {
    this.metaTitle = metaTitle;
    return this;
  }

   /**
   * Get metaTitle
   * @return metaTitle
  **/
  @Schema(description = "")
  public String getMetaTitle() {
    return metaTitle;
  }

  public void setMetaTitle(String metaTitle) {
    this.metaTitle = metaTitle;
  }

  public AnnouncementDetailModel metaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
    return this;
  }

   /**
   * Get metaDescription
   * @return metaDescription
  **/
  @Schema(description = "")
  public String getMetaDescription() {
    return metaDescription;
  }

  public void setMetaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
  }

  public AnnouncementDetailModel title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public AnnouncementDetailModel seoUrl(String seoUrl) {
    this.seoUrl = seoUrl;
    return this;
  }

   /**
   * Get seoUrl
   * @return seoUrl
  **/
  @Schema(description = "")
  public String getSeoUrl() {
    return seoUrl;
  }

  public void setSeoUrl(String seoUrl) {
    this.seoUrl = seoUrl;
  }

  public AnnouncementDetailModel releaseDate(Long releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @Schema(description = "")
  public Long getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(Long releaseDate) {
    this.releaseDate = releaseDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnnouncementDetailModel announcementDetailModel = (AnnouncementDetailModel) o;
    return Objects.equals(this.content, announcementDetailModel.content) &&
        Objects.equals(this.metaTitle, announcementDetailModel.metaTitle) &&
        Objects.equals(this.metaDescription, announcementDetailModel.metaDescription) &&
        Objects.equals(this.title, announcementDetailModel.title) &&
        Objects.equals(this.seoUrl, announcementDetailModel.seoUrl) &&
        Objects.equals(this.releaseDate, announcementDetailModel.releaseDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, metaTitle, metaDescription, title, seoUrl, releaseDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnnouncementDetailModel {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    metaTitle: ").append(toIndentedString(metaTitle)).append("\n");
    sb.append("    metaDescription: ").append(toIndentedString(metaDescription)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    seoUrl: ").append(toIndentedString(seoUrl)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
