/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BugBountyNoticeRequestModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-22T13:33:34.912136+03:00[Europe/Istanbul]")
public class BugBountyNoticeRequestModel {
  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("userEmail")
  private String userEmail = null;

  @SerializedName("diagnosis")
  private String diagnosis = null;

  @SerializedName("host")
  private String host = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("hCaptchaResponse")
  private String hCaptchaResponse = null;

  public BugBountyNoticeRequestModel firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @Schema(required = true, description = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public BugBountyNoticeRequestModel lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @Schema(required = true, description = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public BugBountyNoticeRequestModel email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(required = true, description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public BugBountyNoticeRequestModel phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(description = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public BugBountyNoticeRequestModel userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Get userEmail
   * @return userEmail
  **/
  @Schema(description = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public BugBountyNoticeRequestModel diagnosis(String diagnosis) {
    this.diagnosis = diagnosis;
    return this;
  }

   /**
   * Get diagnosis
   * @return diagnosis
  **/
  @Schema(required = true, description = "")
  public String getDiagnosis() {
    return diagnosis;
  }

  public void setDiagnosis(String diagnosis) {
    this.diagnosis = diagnosis;
  }

  public BugBountyNoticeRequestModel host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @Schema(description = "")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public BugBountyNoticeRequestModel path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @Schema(description = "")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public BugBountyNoticeRequestModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public BugBountyNoticeRequestModel hCaptchaResponse(String hCaptchaResponse) {
    this.hCaptchaResponse = hCaptchaResponse;
    return this;
  }

   /**
   * Get hCaptchaResponse
   * @return hCaptchaResponse
  **/
  @Schema(description = "")
  public String getHCaptchaResponse() {
    return hCaptchaResponse;
  }

  public void setHCaptchaResponse(String hCaptchaResponse) {
    this.hCaptchaResponse = hCaptchaResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BugBountyNoticeRequestModel bugBountyNoticeRequestModel = (BugBountyNoticeRequestModel) o;
    return Objects.equals(this.firstName, bugBountyNoticeRequestModel.firstName) &&
        Objects.equals(this.lastName, bugBountyNoticeRequestModel.lastName) &&
        Objects.equals(this.email, bugBountyNoticeRequestModel.email) &&
        Objects.equals(this.phone, bugBountyNoticeRequestModel.phone) &&
        Objects.equals(this.userEmail, bugBountyNoticeRequestModel.userEmail) &&
        Objects.equals(this.diagnosis, bugBountyNoticeRequestModel.diagnosis) &&
        Objects.equals(this.host, bugBountyNoticeRequestModel.host) &&
        Objects.equals(this.path, bugBountyNoticeRequestModel.path) &&
        Objects.equals(this.description, bugBountyNoticeRequestModel.description) &&
        Objects.equals(this.hCaptchaResponse, bugBountyNoticeRequestModel.hCaptchaResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, email, phone, userEmail, diagnosis, host, path, description, hCaptchaResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BugBountyNoticeRequestModel {\n");
    
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    diagnosis: ").append(toIndentedString(diagnosis)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    hCaptchaResponse: ").append(toIndentedString(hCaptchaResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
