/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LanguageInfoModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * LanguageSettingModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-22T13:33:34.912136+03:00[Europe/Istanbul]")
public class LanguageSettingModel {
  @SerializedName("languageList")
  private List<LanguageInfoModel> languageList = null;

  public LanguageSettingModel languageList(List<LanguageInfoModel> languageList) {
    this.languageList = languageList;
    return this;
  }

  public LanguageSettingModel addLanguageListItem(LanguageInfoModel languageListItem) {
    if (this.languageList == null) {
      this.languageList = new ArrayList<LanguageInfoModel>();
    }
    this.languageList.add(languageListItem);
    return this;
  }

   /**
   * Get languageList
   * @return languageList
  **/
  @Schema(description = "")
  public List<LanguageInfoModel> getLanguageList() {
    return languageList;
  }

  public void setLanguageList(List<LanguageInfoModel> languageList) {
    this.languageList = languageList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LanguageSettingModel languageSettingModel = (LanguageSettingModel) o;
    return Objects.equals(this.languageList, languageSettingModel.languageList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(languageList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LanguageSettingModel {\n");
    
    sb.append("    languageList: ").append(toIndentedString(languageList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
