/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BtcTurkAp30);
  }
}(this, function(expect, BtcTurkAp30) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AkbankDirektLimit', function() {
      beforeEach(function() {
        instance = new BtcTurkAp30.AkbankDirektLimit();
      });

      it('should create an instance of AkbankDirektLimit', function() {
        // TODO: update the code to test AkbankDirektLimit
        expect(instance).to.be.a(BtcTurkAp30.AkbankDirektLimit);
      });

      it('should have the property maxDepositFeeAmount (base name: "maxDepositFeeAmount")', function() {
        // TODO: update the code to test the property maxDepositFeeAmount
        expect(instance).to.have.property('maxDepositFeeAmount');
        // expect(instance.maxDepositFeeAmount).to.be(expectedValueLiteral);
      });

      it('should have the property minDepositAmount (base name: "minDepositAmount")', function() {
        // TODO: update the code to test the property minDepositAmount
        expect(instance).to.have.property('minDepositAmount');
        // expect(instance.minDepositAmount).to.be(expectedValueLiteral);
      });

      it('should have the property maxDepositAmount (base name: "maxDepositAmount")', function() {
        // TODO: update the code to test the property maxDepositAmount
        expect(instance).to.have.property('maxDepositAmount');
        // expect(instance.maxDepositAmount).to.be(expectedValueLiteral);
      });

    });
  });

}));
