/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BtcTurkAp30);
  }
}(this, function(expect, BtcTurkAp30) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AnnouncementDetailModel', function() {
      beforeEach(function() {
        instance = new BtcTurkAp30.AnnouncementDetailModel();
      });

      it('should create an instance of AnnouncementDetailModel', function() {
        // TODO: update the code to test AnnouncementDetailModel
        expect(instance).to.be.a(BtcTurkAp30.AnnouncementDetailModel);
      });

      it('should have the property content (base name: "content")', function() {
        // TODO: update the code to test the property content
        expect(instance).to.have.property('content');
        // expect(instance.content).to.be(expectedValueLiteral);
      });

      it('should have the property metaTitle (base name: "metaTitle")', function() {
        // TODO: update the code to test the property metaTitle
        expect(instance).to.have.property('metaTitle');
        // expect(instance.metaTitle).to.be(expectedValueLiteral);
      });

      it('should have the property metaDescription (base name: "metaDescription")', function() {
        // TODO: update the code to test the property metaDescription
        expect(instance).to.have.property('metaDescription');
        // expect(instance.metaDescription).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property seoUrl (base name: "seoUrl")', function() {
        // TODO: update the code to test the property seoUrl
        expect(instance).to.have.property('seoUrl');
        // expect(instance.seoUrl).to.be(expectedValueLiteral);
      });

      it('should have the property releaseDate (base name: "releaseDate")', function() {
        // TODO: update the code to test the property releaseDate
        expect(instance).to.have.property('releaseDate');
        // expect(instance.releaseDate).to.be(expectedValueLiteral);
      });

    });
  });

}));
