/*
 * BtcTurk API 3.0
 * White label exchange API documentation.
 *
 * OpenAPI spec version: 3.0
 * Contact: development@btctrader.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BtcTurkAp30);
  }
}(this, function(expect, BtcTurkAp30) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LimitOutputModel', function() {
      beforeEach(function() {
        instance = new BtcTurkAp30.LimitOutputModel();
      });

      it('should create an instance of LimitOutputModel', function() {
        // TODO: update the code to test LimitOutputModel
        expect(instance).to.be.a(BtcTurkAp30.LimitOutputModel);
      });

      it('should have the property papara (base name: "papara")', function() {
        // TODO: update the code to test the property papara
        expect(instance).to.have.property('papara');
        // expect(instance.papara).to.be(expectedValueLiteral);
      });

      it('should have the property akbankDirekt (base name: "akbankDirekt")', function() {
        // TODO: update the code to test the property akbankDirekt
        expect(instance).to.have.property('akbankDirekt');
        // expect(instance.akbankDirekt).to.be(expectedValueLiteral);
      });

      it('should have the property bank (base name: "bank")', function() {
        // TODO: update the code to test the property bank
        expect(instance).to.have.property('bank');
        // expect(instance.bank).to.be(expectedValueLiteral);
      });

      it('should have the property currencies (base name: "currencies")', function() {
        // TODO: update the code to test the property currencies
        expect(instance).to.have.property('currencies');
        // expect(instance.currencies).to.be(expectedValueLiteral);
      });

      it('should have the property pairs (base name: "pairs")', function() {
        // TODO: update the code to test the property pairs
        expect(instance).to.have.property('pairs');
        // expect(instance.pairs).to.be(expectedValueLiteral);
      });

      it('should have the property countryCode (base name: "countryCode")', function() {
        // TODO: update the code to test the property countryCode
        expect(instance).to.have.property('countryCode');
        // expect(instance.countryCode).to.be(expectedValueLiteral);
      });

    });
  });

}));
