# coding: utf-8

"""
    BtcTurk API 3.0

    White label exchange API documentation.  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: development@btctrader.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.limit_type import LimitType  # noqa: E501
from swagger_client.rest import ApiException


class TestLimitType(unittest.TestCase):
    """LimitType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLimitType(self):
        """Test LimitType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.limit_type.LimitType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
