# coding: utf-8

"""
    BtcTurk API 3.0

    White label exchange API documentation.  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: development@btctrader.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.home_api import HomeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHomeApi(unittest.TestCase):
    """HomeApi unit test stubs"""

    def setUp(self):
        self.api = HomeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_resources_language_get(self):
        """Test case for api_resources_language_get

        """
        pass

    def test_api_resources_language_json_get(self):
        """Test case for api_resources_language_json_get

        """
        pass

    def test_api_resources_location_get(self):
        """Test case for api_resources_location_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
