# coding: utf-8

"""
    BtcTurk API 3.0

    White label exchange API documentation.  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: development@btctrader.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.report_api import ReportApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportApi(unittest.TestCase):
    """ReportApi unit test stubs"""

    def setUp(self):
        self.api = ReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v3_report_deposit_and_withdrawal_post(self):
        """Test case for api_v3_report_deposit_and_withdrawal_post

        """
        pass

    def test_api_v3_report_get(self):
        """Test case for api_v3_report_get

        """
        pass

    def test_api_v3_report_trade_history_post(self):
        """Test case for api_v3_report_trade_history_post

        """
        pass

    def test_api_v3_report_transaction_history_post(self):
        """Test case for api_v3_report_transaction_history_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
