# coding: utf-8

"""
    BtcTurk API 3.0

    White label exchange API documentation.  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: development@btctrader.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.problem_details import ProblemDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestProblemDetails(unittest.TestCase):
    """ProblemDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemDetails(self):
        """Test ProblemDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.problem_details.ProblemDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
