# coding: utf-8

"""
    BtcTurk API 3.0

    White label exchange API documentation.  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: development@btctrader.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v3_account_address_put(self):
        """Test case for api_v3_account_address_put

        """
        pass

    def test_api_v3_account_buy_sell_ınfo_get(self):
        """Test case for api_v3_account_buy_sell_ınfo_get

        """
        pass

    def test_api_v3_account_features_get(self):
        """Test case for api_v3_account_features_get

        """
        pass

    def test_api_v3_account_limits_get(self):
        """Test case for api_v3_account_limits_get

        """
        pass

    def test_api_v3_account_pdpa_post(self):
        """Test case for api_v3_account_pdpa_post

        """
        pass

    def test_api_v3_account_splash_screen_login_post(self):
        """Test case for api_v3_account_splash_screen_login_post

        """
        pass

    def test_api_v3_account_trade_fee_rates_get(self):
        """Test case for api_v3_account_trade_fee_rates_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
