# coding: utf-8

"""
    BtcTurk API 3.0

    White label exchange API documentation.  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: development@btctrader.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.support_platforms_api import SupportPlatformsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSupportPlatformsApi(unittest.TestCase):
    """SupportPlatformsApi unit test stubs"""

    def setUp(self):
        self.api = SupportPlatformsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v3_support_platforms_get(self):
        """Test case for api_v3_support_platforms_get

        """
        pass

    def test_api_v3_support_platforms_zendesk_chat_jwt_platform_get(self):
        """Test case for api_v3_support_platforms_zendesk_chat_jwt_platform_get

        """
        pass

    def test_api_v3_support_platforms_zendesk_mobile_jwt_platform_post(self):
        """Test case for api_v3_support_platforms_zendesk_mobile_jwt_platform_post

        """
        pass

    def test_api_v3_support_platforms_zendesk_sessions_post(self):
        """Test case for api_v3_support_platforms_zendesk_sessions_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
