# coding: utf-8

"""
    BtcTurk API 3.0

    White label exchange API documentation.  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: development@btctrader.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.feedback_api import FeedbackApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFeedbackApi(unittest.TestCase):
    """FeedbackApi unit test stubs"""

    def setUp(self):
        self.api = FeedbackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v3_feedback_app_rating_post(self):
        """Test case for api_v3_feedback_app_rating_post

        """
        pass

    def test_api_v3_feedback_support_platforms_get(self):
        """Test case for api_v3_feedback_support_platforms_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
